// <auto-generated />
namespace FilExplorer.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddFolderManyRS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFolderManyRS));
        
        string IMigrationMetadata.Id
        {
            get { return "201509150157233_AddFolderManyRS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
