// <auto-generated />
namespace FilExplorer.DataLayer.Migrations2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ADDFOLDERModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDFOLDERModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201509132045325_ADDFOLDERModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
