// <auto-generated />
namespace FilExplorer.DataLayer.Migrations2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ADDFOLDERANDFILE5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDFOLDERANDFILE5));
        
        string IMigrationMetadata.Id
        {
            get { return "201509132038219_ADDFOLDERANDFILE5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
